stages:
  - build
  - release

build_job:
  stage: build
  script:
    - apk --update add openjdk11
    - ls -lah
    - mkdir .theme
    - mkdir .theme/META-INF
    - mkdir .theme/theme
    - cd .theme/
    - jar cvf dataplant-card-theme.jar *
  artifacts:
    paths:
      - dataplant-card-theme.jar

release_job:
  stage: release
  script:
    - ls -lah