stages:
  - build
  - release

build_job:
  stage: build
  before_script:
    - echo $CI_JOB_ID
    # Writing GE_JOB_ID variable to environment file, will need the value in the next stage.
    - echo GE_JOB_ID=$CI_JOB_ID >> generate_jar.env
  script:
    - apk --update add openjdk11
    - ls -lah
    - mkdir theme
    - mkdir theme/META-INF
    - ls -lah
    - ls -lah theme/
    - cp keycloak-themes.json theme/META-INF/
    - cp -r dataplant-card-theme theme/
    - ls -lah theme/META-INF
    - ls -lah theme/
    - jar cvf dataplant-card-theme.jar *
    - echo "Theme Jar file generated successfully."
  artifacts:
    paths:
      - theme/dataplant-card-theme.jar
    reports:
      dotenv:  generate_jar.env

release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: build_job
      artifacts: true
  script:
    - echo 'running release_job'
    - echo 'Previous Job ID is printed below'
    - echo $GE_JOB_ID
    - ls -lah
  release:
    name: 'Dataplant Card Theme $CI_COMMIT_SHORT_SHA'
    description: 'Official Dataplant Keycloak theme'
    tag_name: '$CI_COMMIT_SHORT_SHA'
    assets:
      links:
        - name: 'Jar File'
          url: 'https://git.bwcloud.uni-freiburg.de//marcel/dataplant-keycloak-theme/-/jobs/${GE_JOB_ID}/artifacts/file/theme/dataplant-card-theme.jar'

