stages:
  - build
  - release
  - release_package

build_job:
  stage: build
  before_script:
    - echo $CI_JOB_ID
    # Writing GE_JOB_ID variable to environment file, will need the value in the next stage.
    - echo GE_JOB_ID=$CI_JOB_ID >> generate_jar.env
  script:
    - apk --update add openjdk11
    - mkdir -p build/META-INF
    - cp keycloak-themes.json build/META-INF/
    - cp -r dataplant-card-theme build/theme
    - ls -lah build/META-INF
    - ls -lah build/
    - cd build/
    - jar cvf dataplant-card-theme.jar *
    - ls -lahR
    - echo "Theme Jar file generated successfully."
  artifacts:
    paths:
      - build/dataplant-card-theme.jar
    reports:
      dotenv:  generate_jar.env

release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: build_job
      artifacts: true
  script:
    - echo 'running release_job'
    - echo 'Previous Job ID is printed below'
    - echo $GE_JOB_ID
    - ls -lah
  release:
    name: 'Dataplant Card Theme $CI_COMMIT_SHORT_SHA'
    description: 'Official Dataplant Keycloak theme'
    tag_name: '$CI_COMMIT_SHORT_SHA'
    assets:
      links:
        - name: 'Jar File'
          url: 'https://git.bwcloud.uni-freiburg.de/marcel/dataplant-keycloak-theme/-/jobs/${GE_JOB_ID}/artifacts/file/build/dataplant-card-theme.jar'

release_package:
  stage: release_package
  needs:
    - job: build_job
      artifacts: true
  script:
    - apk --update add curl
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file build/dataplant-card-theme.jar "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/Dataplant-Card-Theme/latest/dataplant-card-theme.jar"'

