version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.0
    container_name: keycloak
    env_file:
      - .env.keycloak
    environment:
      PROXY_ADDRESS_FORWARDING: "false"
    entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev"]
    ports:
      - 8080:8080
    volumes:
      - /home/marcel/GIT/dataplant-keycloak-theme/dataplant-card-theme/:/opt/keycloak/themes/dtheme/:rw
